"""Changes in database and added entities

Revision ID: 2ca2adee382f
Revises: 
Create Date: 2026-07-07 01:27:29.587869

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2ca2adee382f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_invitations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_project', sa.Integer(), nullable=False),
    sa.Column('id_inviter', sa.Integer(), nullable=False),
    sa.Column('id_invitee', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=100), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'ACCEPTED', 'REJECTED', name='invitationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['id_invitee'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_inviter'], ['users.id'], ),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_invitations_id'), 'project_invitations', ['id'], unique=False)
    op.drop_table('notifications')
    op.drop_table('requests')
    op.alter_column('collaborators', 'role',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('collaborators', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collaborators', 'id_project',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('collaborators', 'joined_at',
               existing_type=postgresql.TIMESTAMP(),
               type_=sa.DateTime(timezone=True),
               nullable=False)
    op.create_index(op.f('ix_collaborators_id'), 'collaborators', ['id'], unique=False)
    op.drop_constraint(op.f('collaborators_id_project_fkey'), 'collaborators', type_='foreignkey')
    op.drop_constraint(op.f('collaborators_id_user_fkey'), 'collaborators', type_='foreignkey')
    op.create_foreign_key(None, 'collaborators', 'users', ['id_user'], ['id'])
    op.create_foreign_key(None, 'collaborators', 'projects', ['id_project'], ['id'])
    op.alter_column('project_tags', 'id_project',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('project_tags', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_project_tags_id'), 'project_tags', ['id'], unique=False)
    op.drop_constraint(op.f('project_tags_id_project_fkey'), 'project_tags', type_='foreignkey')
    op.create_foreign_key(None, 'project_tags', 'projects', ['id_project'], ['id'])
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'description',
               existing_type=sa.TEXT(),
               type_=sa.String(length=500),
               existing_nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('projects', 'max_collaborators',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('projects', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.create_index(op.f('ix_projects_id'), 'projects', ['id'], unique=False)
    op.drop_constraint(op.f('projects_owner_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['owner_id'], ['id'])
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'bio',
               existing_type=sa.TEXT(),
               type_=sa.String(),
               existing_nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('users', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.alter_column('users', 'date_updated',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'date_created',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('users', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.String(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('users', 'last_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'first_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_owner_id_fkey'), 'projects', 'users', ['owner_id'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_projects_id'), table_name='projects')
    op.alter_column('projects', 'owner_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'max_collaborators',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('projects', 'status',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('projects', 'description',
               existing_type=sa.String(length=500),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('projects', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(None, 'project_tags', type_='foreignkey')
    op.create_foreign_key(op.f('project_tags_id_project_fkey'), 'project_tags', 'projects', ['id_project'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_project_tags_id'), table_name='project_tags')
    op.alter_column('project_tags', 'tag',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('project_tags', 'id_project',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_constraint(None, 'collaborators', type_='foreignkey')
    op.drop_constraint(None, 'collaborators', type_='foreignkey')
    op.create_foreign_key(op.f('collaborators_id_user_fkey'), 'collaborators', 'users', ['id_user'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('collaborators_id_project_fkey'), 'collaborators', 'projects', ['id_project'], ['id'], deferrable=True)
    op.drop_index(op.f('ix_collaborators_id'), table_name='collaborators')
    op.alter_column('collaborators', 'joined_at',
               existing_type=sa.DateTime(timezone=True),
               type_=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('collaborators', 'id_project',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collaborators', 'id_user',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('collaborators', 'role',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.create_table('requests',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('id_project', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('review_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('reviewed_by', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_project'], ['projects.id'], name=op.f('requests_id_project_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name=op.f('requests_id_user_fkey'), deferrable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], name=op.f('requests_reviewed_by_fkey'), deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('requests_pkey'))
    )
    op.create_table('notifications',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('id_user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('content', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('read', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['id_user'], ['users.id'], name=op.f('notifications_id_user_fkey'), deferrable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    op.drop_index(op.f('ix_project_invitations_id'), table_name='project_invitations')
    op.drop_table('project_invitations')
    # ### end Alembic commands ###
