"""Changes in project invitations entity

Revision ID: 2db0665534e7
Revises: 2ca2adee382f
Create Date: 2026-07-07 05:26:23.518287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2db0665534e7'
down_revision: Union[str, Sequence[str], None] = '2ca2adee382f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_invitations', sa.Column('token', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project_invitations', 'token')
    # ### end Alembic commands ###
