"""deleted config in subtask field in task

Revision ID: a27b632c89f8
Revises: fbaf3bcd10fb
Create Date: 2026-08-06 22:36:22.013126

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a27b632c89f8'
down_revision: Union[str, Sequence[str], None] = 'fbaf3bcd10fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
