"""removed field in Task

Revision ID: d8f92b25a8e0
Revises: 0e6cab45932a
Create Date: 2026-08-04 17:10:07.627833

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8f92b25a8e0'
down_revision: Union[str, Sequence[str], None] = '0e6cab45932a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'comments')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('comments', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
