"""added config in subtasks in model task

Revision ID: fbaf3bcd10fb
Revises: ca3f7c5e6685
Create Date: 2026-08-06 22:30:08.031443

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fbaf3bcd10fb'
down_revision: Union[str, Sequence[str], None] = 'ca3f7c5e6685'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
